[phases.setup]
nixPkgs = ["python39", "postgresql", "redis"]
[phases.install]
cmds = ["pip install -r requirements.txt"]
[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate --noinput"
]
[start]
cmd = "daphne radar_monitoring.asgi:application --port $PORT --bind 0.0.0.0"
[variables]
NIXPACKS_PYTHON_VERSION = "3.9"