services:
  - type: web
    name: radar-monitoring
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: radar_monitoring.settings
      - key: MYSQLDATABASE
        value: railway
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: qJtTRwKuUqEACEHJugJQlyCpRlbsNNpb
      - key: MYSQLHOST
        value: mysql.railway.internal
      - key: MYSQLPORT
        value: 3306
      - key: DEBUG
        value: "False"
